package chapter_leetcode.easy;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**  
 * 389. Find the Difference   Add to List QuestionEditorial Solution  My Submissions
Total Accepted: 47624
Total Submissions: 93834
Difficulty: Easy
Contributors: Admin

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.   
 *  
 * @author 郑元浩 
 * @date 2017年1月18日 上午11:49:22 
 */
public class FindtheDifference389 {

	public static void main(String[] args) {
		System.out.println(findTheDifference("abcd", "abdce"));
		System.out.println(findTheDifference2("abcd", "abdce"));
	}
	
	/**
	 * 将s中的每个字符保存到hashmap中，key为每个char，value为其出现次数
	 * 将t中的每个字符在hashmap中进行查询，如果没有key，则就是这个数，如果有key，则将其value减1，判断此时value为负值表示就是多出来的一个char。
	 * @param s
	 * @param t
	 * @return
	 */
	public static char findTheDifference(String s, String t) {
		Character result = ' ';
        Map<Character, Integer> map = new HashMap<Character, Integer>();
        for(Character ch : s.toCharArray()){ // 将s中的每个char保存到hashmap中
        	if (map.containsKey(ch)) {
				map.put(ch, map.get(ch) + 1);
			} else {
				map.put(ch, 1);
			}
        }
        for(Character ch : t.toCharArray()){ // 将t中的每个char在hashmap中进行比较判断
        	if (!map.containsKey(ch)) { // 不包含该元素直接输出
        		result = ch;
				return ch;
			} else {
				map.put(ch, map.get(ch) - 1);
				if(map.get(ch) < 0){
					result = ch;
					return ch;
				}
			}
        }
        return result;
    }
	
	/**
	 * 将s和t都保存在list中，然后遍历s的list，将t中存在的所有s的元素删除，剩余的那个元素就是最终要找的那个元素了。
	 * @param s
	 * @param t
	 * @return
	 */
	public static char findTheDifference2(String s, String t) {
		List<Character> tList = new ArrayList<Character>();
		for (Character c : t.toCharArray()) {
			tList.add(c);
		}
		for (Character c : s.toCharArray()) {
			tList.remove(c);
		}
		return tList.get(0);
	}

}
